# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
INTER_RATE: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'clothing.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'


field_separator: "\t"
k_neighbour: 1
is_neighbour: True
embedding_size: 64
feat_embed_dim: 64
cf_model: lightgcn
meta_weight: [0.5]
n_meta_layer: [8]
#att_weight: [ 0.1 ,0.05 ,0.2 ,0.3 ,0.5 ]
#att_init: [ 0.3,0.1,0.2,0.4,0.5 ]
n_ui_layers: [10]
n_mm_layers: [2]
reg_weight: [1e-06]

#meta_weight: [ 1,0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1 ]
#n_meta_layer: [ 8, 7, 6]
##att_weight: [ 0.1 ,0.05 ,0.2 ,0.3 ,0.5 ]
##att_init: [ 0.3,0.1,0.2,0.4,0.5 ]
#n_ui_layers: [5]
#n_mm_layers: [ 2, 3 ]
#reg_weight: [ 1e-06, 1e-05 ]
hyper_parameters: [ "n_ui_layers", "n_mm_layers",  "reg_weight",'meta_weight','n_meta_layer' ]
